version: 2
machine:
  node:
    version: 8.11.3
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Run Test
          command: |
            yarn test
      - run:
          name: 'Upload coverage'
          command: yarn coverage -- -t $CODECOV_TOKEN
